module.exports = {
    errors: {
        accountNotFound: 'Your account is not found. Please check again.',
        validationError: 'Invalid data sent.',
        disconnectOneMore: 'Cannot close account. Your account has only one or fewer.',
        disconnectLine: 'Unable to close your LINE LIFF account. Please check.',
        connectPlatform: 'Please check the connected platform.',
        wrong: 'Hash is wrong!',
        badRequest: 'Bad request',
        memberIsNotConnect: 'Member is not connected to LINE!',
        accountIsNotConnect: 'Account is not connected to LINE!',
        actionNotFound: 'Action not found',
        accountIsUse: 'This account is already in use.',
        transactionCreatingAccount: 'Error in transaction creating account',
        adapterLineNotFound: 'Adapter Line not found',
        updateConsent: 'Error updating consent',
        consentNotFound: 'Consent not found',
        contentNotFound: 'Content not found',
        cAccountNotFound: 'This account is not found',
        categoriesGameNotFound: 'Categories game not found',
        termAndConditionNotFound: 'Term and condition data not found',
        usernameIsExist: 'Username already exists',
        connectedExist: 'Your {0} account is already connected.',
        tokenError: 'token error',
        secretTempExpired: 'secret temp expired',
        invalidInputTemporary: 'Invalid input temporary',
        requiredUpload:'required file upload',
        uploadObsFailed:'Upload OBS failed',
        // Add other error messages as needed
    },
    success: {
        getProfileSuccess: 'Profile retrieval successful.',
        updateProfileSuccess: 'Profile update successful.',
        forgotPasswordSuccess: 'Password reset successful.',
        updateCodeSuccess: 'Company update successful.',
        disconnectSuccess: 'Account closure successful.',
        connectSuccess: 'Account connection successful.',
        accountVerifySuccess: 'Account verification success',
        memberIsConnectSuccess: 'Member is connected to LINE',
        accountRegistrationSuccess: 'Account registration successful',
        loginSuccess: 'Login successful',
        versionConsentSuccess: 'Version consent is up to date',
        acceptStatus: 'Never clicked',
        acceptNotVersionStatus: 'Clicked, but version does not match',
        saveConsentSuccess: 'Consent saved successfully',
        getContentSuccess: 'Content retrieval successful',
        getGealthCheckSuccess: 'Get all questions and answers successful',
        createQuestionSuccess: 'Question creation successful',
        createAnswerSuccess: 'Answer creation successful',
        saveAnswerSuccess: 'Answer saved successful',
        createPersonaIconSuccess: 'Persona icon creation successful',
        getAllPersonaIconSuccess: 'Get all persona icons successful',
        getHistoryPasswordSuccess: 'Get history password',
        getTermAndConditionSuccess: 'Term and condition data',
        userNameCanBeUsed: 'Username can be used',
        sendOtpSuccess: 'Sending OTP successful',
        verifyOtpSuccess: 'OTP verification successful',
        acceptSuccess: 'Accept successful',
        rejectSuccess: 'Reject successful',
        getCategoriesSuccess: 'Get categories successful',
        getGameBoardSuccess: 'Get game board successful',
        lockPasswordSuccess: 'lock password successful',
        // Add other success messages as needed
    }
};
