module.exports = {
    errors: {
        accountNotFound: 'บัญชีของท่านไม่ถูกต้อง กรุณาตรวจสอบ',
        validationError: 'ข้อมูลที่ส่งมาไม่ถูกต้อง',
        disconnectOneMore: 'ไม่สามารถปิดบัญชีได้ เนื่องจากบัญชีของท่านมีแค่ 1 บัญชีหรือน้อยกว่า',
        disconnectLine: 'ไม่สามารถปิดบัญชี LINE LIFF ของท่านได้ กรุณาตรวจสอบ',
        connectPlatform: 'กรุณาตรวจสอบ connect platform',
        wrong :'hash is wrong!',
        badRequest: 'bad request',
        memberIsNotConnect:'Member is not connect line!',
        accountIsNotConnect:'account is not connect line!',
        actionNotFound:'Action not found',
        accountIsUse: 'บัญชีนี้ถูกใช้งานแล้ว',
        transactionCreatingAccount: 'error transaction creating account',
        adapterLineNotFound: 'ไม่พบ Adapter Line',
        updateConsent: 'error update consent',
        consentNotFound: 'ไม่มีพบ consent',
        cAccountNotFound: 'ไม่พบ account นี้',
        termAndConditionNotFound: 'ไม่พบข้อมูล term and condition',
        usernameIsExist: 'username is exist already',
        // เพิ่มข้อความข้อผิดพลาดอื่น ๆ ตรงนี้ตามต้องการ
    },
    success: {
        getProfileSuccess: 'เรียกดูโปรไฟล์เรียบร้อยแล้ว',
        updateProfileSuccess: 'อัพเดตโปรไฟล์สำเร็จ',
        forgotPasswordSuccess: 'รีเซ็ตรหัสผ่านสำเร็จ',
        updateCodeSuccess: 'อัพเดต company สำเร็จ',
        disconnectSuccess: 'ปิดบัญชีสำเร็จ',
        connectSuccess: 'เชื่อมต่อบัญชีสำเร็จ',
        accountVerifySuccess: 'account verify success',
        memberIsConnectSuccess:'Member is connect line',
        accountRegistrationSuccess: 'Account registration successful',
        loginSuccess: 'Login successful',
        versionConsentSuccess: 'version consent เป็น version ล่าสุดแล้ว',
        acceptStatus: 'ไม่เคยกด',
        acceptNotVersionStatus: 'เคยกด แต่ version ไม่ตรงกัน',
        saveConsentSuccess: 'Save consent successful',
        getContentSuccess: 'Get content successful',
        getGealthCheckSuccess: 'Get all questions and answers successful',
        createQuestionSuccess: 'create question successful',
        createAnswerSuccess: 'Create answer successful',
        saveAnswerSuccess: 'Save answer successful',
        createPersonaIconSuccess:'create persona icon successful',
        getAllPersonaIconSuccess: 'Get all persona icon successful',
        getHistoryPasswordSuccess: 'get history password',
        getTermAndConditionSuccess: 'ข้อมูล term and condition',
        userNameCanBeUsed: 'username can be used',
        sendOtpSuccess: 'sending otp successful',
        verifyOtpSuccess: 'OTP verification successful',
        acceptSuccess: 'Accept successful',
        rejectSuccess: 'Reject successful',
        // เพิ่มข้อความสำเร็จอื่น ๆ ตรงนี้ตามต้องการ
    }
};
